version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/geospatial:latest
    steps:
      - checkout
      - run:
          command: |
            R -e "devtools::install_deps(dependencies = TRUE)"
            R -e "devtools::install_github('mangothecat/goodpractice')"
            R -e "devtools::install_github('r-lib/testthat')"
            R -e "install.packages('DT')"
      - run:
          command: |
            R -e "devtools::check(cran = FALSE)"
      - run:
          no_output_timeout: 20m
          command: |
            mkdir /root/main/artifacts
            R -e "devtools::install()"
            R -e "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert=TRUE, value=TRUE))"
            R -e "covr::codecov(quiet = FALSE)"
            R CMD Rd2pdf --force --output='/root/main/artifacts/leri-manual.pdf' .
      - store_artifacts:
          path: /root/main/artifacts/
          destination: artifacts
